# Generated by Django 4.1.6 on 2023-12-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uzuklar',
            name='context',
        ),
        migrations.AddField(
            model_name='uzuklar',
            name='narxi',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
