# Generated by Django 4.1.6 on 2023-12-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_uzuklar_context_uzuklar_narxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzuklar',
            name='murojat',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
