# Generated by Django 4.1.6 on 2023-12-10 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_uzuklar_murojat'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzuklar',
            name='tag',
            field=models.CharField(choices=[('Uzuklar', 'Uzuklar'), ('Ziraklar', 'Ziraklar'), ('Braslet', 'Braslet'), ('Sipochka', 'Sipochka')], default='Uzuklar', max_length=50),
        ),
    ]
