# Generated by Django 4.1.6 on 2023-12-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_uzuklar_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uzuklar',
            new_name='Goldenshop',
        ),
    ]
