# Generated by Django 4.1.6 on 2023-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_uzuklar_goldenshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenshop',
            name='size',
            field=models.CharField(default='', max_length=255),
        ),
    ]
