# Generated by Django 4.1.6 on 2023-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_goldenshop_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenshop',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
