# Generated by Django 5.0 on 2023-12-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_goldenshop_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenshop',
            name='tag',
            field=models.CharField(choices=[('Uzuklar', 'Uzuklar'), ('Braslet', 'Braslet'), ('Sipochka', 'Sipochka')], default='Uzuklar', max_length=50),
        ),
    ]
