# Generated by Django 5.0 on 2023-12-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_goldenshop_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldenshop',
            name='tag',
        ),
    ]
