# Generated by Django 5.0 on 2023-12-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_goldenshop_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goldenshop',
            new_name='Uzuklar',
        ),
    ]
