# Generated by Django 5.0 on 2023-12-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodimlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodimlar',
            name='yosh',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
